### ISSUE TITLE
Errors on IE11 with promises when the SDK is loaded

### ISSUE THREAD

**Issue by remiwimi** [TankerHQ/sdk-js#3]
## Issue

What is the current behavior?
We have an error with the usage of Promises when the Tanker SDK is loaded.
We use es6-promises to polyfill the promises. When the SDK is not loaded, the promises works fine with IE11.
It works well with other browsers.

What is the expected behavior?
No errors on the promises.

Can you provide a list of simple steps that reproduce the problem?

Do you have any logs you can provide? (from the browser's console for instance)

"Unhandled promise rejection TypeError: [object Object] is not iterable!"

## Environment

Tanker SDK version: 1.9.3
Web browser: Internet Explorer
Web browser version: 11.0.9600
OS: Windows 8.1

**Comment by remiwimi** [comment]
Are is our code with the Promise.all(), 

`oResponse.devices = await Promise.all(oResponse.devices.map(function (devices_item:any) { return Model.Device.Build(devices_item); }));`

The Model.Device.Build function returns:
```
public static async Build(oDevice: any): Promise<Device>
{
    if (Model.Device.prototype.isPrototypeOf(oDevice))
    {
        console.warn("Device - Trying to instantiate an object that is already an instance of Device! Returning instance.");
        return oDevice;
    }
    
     oDevice = await this._format(oDevice);
     return new Device(oDevice);
}
```

As you can see, not Tanker code is called (the _format function just formats a date).
This code works well when the Tanker SDK is not loaded. 
By logging the Model.Device.Build(devices_item) return, I have a difference : 

Without the SDK
![object not armoured promise ie](https://user-images.githubusercontent.com/46372521/51314387-de8c8380-1a4f-11e9-83ec-e008d4fa88b5.png)

With the SDK : 
![object armoured promise ie](https://user-images.githubusercontent.com/46372521/51314414-eba97280-1a4f-11e9-804c-9bfef08f93e7.png)

Is there anything that could override the Promises definition on your side ?

**Comment by jeremad** [comment]
We are investigating, and thanks to your input we indeed found something regarding an unexpected interaction with the polyfill and tanker.
As a quickfix could you try to import tanker's UMD before the `es6-promises` polyfill?

We are currently investigating deeper to fix the root issue.

**Comment by remiwimi** [comment]
Thanks it works :) 
Keep us updated when the root issue is fixed

**Comment by jeremad** [comment]
We have identified the issue, we will release a 1.9.4 next week

**Comment by jeremad** [comment]
v1.9.4 is out, could you test if it fixes your issue?
Thqnk you!

**Comment by remiwimi** [comment]
Yes the update fixed it :) Thanks
