### ISSUE TITLE
Losing device on Chrome

### ISSUE THREAD

**Issue by remiwimi** [TankerHQ/sdk-js#4]
## Issue

What is the current behavior?
I register a device on Chrome and after a period on inactivity on the account (no connection for ~2 weeks), the device is not registered anymore.
The Chrome have probably been updated during this period.

What is the expected behavior?
The device should still be registered

Can you provide a list of simple steps that reproduce the problem?
Create a new device on Chrome, do not use it for several days/weeks, try to use this device.

Do you have any logs you can provide? (from the browser's console for instance)
No logs

## Environment

Tanker SDK version: 1.9.3
Web browser: Chrome
Web browser version: 71.0.3578
OS: Mac

**Comment by jeremad** [comment]
Hello @remiwimi , thank you for taking the time to report your issue.
I have tried to perform an update of chrome, and my device is still recognized. I will let my chrome rest for a couple of weeks, and try again to reproduce your issue.
In the meantime, my best guess is that in this two weeks span you flushed your chrome's cache. To avoid this kind of issue you can use the "unlock" by password, so you can easily recover your accounts on any device:
https://tanker.io/docs/latest/guide/seamless-device-unlocking/

**Comment by jeremad** [comment]
Also it is worth noting that the browser may decide by itself to delete storage data (where your tanker data is stored) for instance if your disk space is low

**Comment by jeremad** [comment]
I tried it, and I was able to log without unlock. I'm afraid this is an issue of the browser unilaterally deleting storage. We are looking into a solution with a more persistent storage, but it will not be in a near future.
Like I said before, for the moment you can bypass this browser issue with the unlock.
Let me know if you need help with that!
