### ISSUE TITLE
invalid_delegation_signature when opening

### ISSUE THREAD

**Issue by remiwimi** [TankerHQ/sdk-js#5]
## Issue

What is the current behavior?
When calling the tanker.open we sometimes have an 'invalid_delegation_signature' error.
The error occurs when we create a new account so it is the first user added to the trustchain.

What is the expected behavior?
The session should open correctly.

Can you provide a list of simple steps that reproduce the problem?
Try to open a tanker session.

Do you have any logs you can provide? (from the browser's console for instance)
![screenshot 2019-01-16 at 17 34 08](https://user-images.githubusercontent.com/46372521/51334298-d51b0f80-1a7f-11e9-8a77-3a6b6131aeed.png)

Here is the trustchain_id: 
p1zhoAqXoXnVqynpmIx5t8rVFNXWmkKh7/ovCqxBVVo=
The user_token : 
eyJlcGhlbWVyYWxfcHVibGljX3NpZ25hdHVyZV9rZXkiOiIvVW5adWpmZGdvcHk3MnlndG1WVWd6M2NmMDBPaDlaYTlsVENSNjlRemhzPSIsImVwaGVtZXJhbF9wcml2YXRlX3NpZ25hdHVyZV9rZXkiOiJIMFk5VWtPN3AwOTV6N0M2MXNndDV2U05BZTlRTDhIUU83NGY0OENjM0J6OVNkbTZOOTJDaW5MdmJLQzJaVlNEUGR4L1RRNkgxbHIyVk1KSHIxRE9Hdz09IiwidXNlcl9pZCI6ImNvT2hPOXVlTXdVcFNVY1J0MEtDL29PSU5Wdy9IanA1M3VSUG5hdkVYQ0k9IiwiZGVsZWdhdGlvbl9zaWduYXR1cmUiOiIxMUdWNW5wVWxyQmJlcGc4N29EOElHRG5pdVRMM3RyMC9sVVRlcTBNc3BrV01CbDR3OHpmYmRGcEM5ZWpMbVRqdGtCVkdieldFVUU3NmJPcTUraXZDZz09IiwidXNlcl9zZWNyZXQiOiJSYld4NXRSMVBsVUpNN0dMaitBS0pJc2k5TWYrcWNNb1h5VFgyOHdCR3dnPSJ9

## Environment

Tanker SDK version: For this trustchain it's the 1.7 but the bug also occurs in 1.9.3
Web browser: All
Web browser version:
OS: All

**Comment by jeremad** [comment]
Hello,
After investigation the UserToken you use, does not correspond to the trustchain ID you provided. It matches the trustchain `v1TBQiwv92V/jzHe15rqiW1eZq6dwOLRHoekJ8CBf6I= `. So we suspect that there was a mismatch between the trustchain ID client side and server side.

**Comment by remiwimi** [comment]
Hi,
Does the name of a trustchain in the dashboard has an importance ? Because it appears that the trustchain linked to the userToken (v1TBQiwv92V/jzHe15rqiW1eZq6dwOLRHoekJ8CBf6I=) and the one linked to our account have the same name.

**Comment by jeremad** [comment]
Hello Remi,

Names are only for reference in the dashboard, there are never used Tanker side.

We have not this user in our databases. What I think happened:
- You created a token with trustchainA
- You try to do a open with this token on trustchainB
- It does not work, the user is never created

I'm sorry I cannot help you more than that.
I need a way to reproduce the bug, otherwise I can only guess.
