### ISSUE TITLE
Error when unlocking device with password or changing unlock password

### ISSUE THREAD

**Issue by remiwimi** [TankerHQ/sdk-js#6]
## Issue

What is the current behavior?
We have an account where users can not validate or change the unlock password since this morning. The trustchain of this account is : IEIwFT3/JIOBsvjoJ/NujhBi2pNmoXgu+3cunIlqvgw=
We tested on other accounts and everything works well.
It seems that the process get stuck in the unlockCurrentDevice.

Can you provide a list of simple steps that reproduce the problem?
Not really, works well with other accounts.

Do you have any logs you can provide? (from the browser's console for instance)
There is no error in the console.

## Environment

Tanker SDK version: 10.1
Web browser: Every browsers
Web browser version:
OS: Every OS

**Comment by quentinvernot** [comment]
Hello, thanks for the issue,

There haven't been any recent server-side changes that could have causes it to suddenly happen. Did this user already exist before this morning? Do you know if `tanker.setupUnlock({ password })` had been called for this user? We can find out if you give us the user's id.

You mentioned that the process is 'stuck', do you mean that `tanker.unlockCurrentDevice` never returns or throws `InvalidPassword`?

Can you provide a snippet of the code around the call? Maybe the wrong error gets thrown somehow and is silenced or ignored.

**Comment by remiwimi** [comment]
Here are the two users that have the issue (that we are aware of) : local-1151251 and local-1153888
Both of this users already exist before this morning and they had already validated other devices.

There is indeed no errors, here is the js code : 
```
try {
	await _tanker.unlockCurrentDevice({password: sUnlockPassword});
	callback(true);
} catch (e)
{
       console.error('Error during unlock with password', e);

	if (e.name.toString() !== 'InvalidUnlockPassword')
		logErrorEvent('unlock_current_device_with_password', {error_detail: e});

	if (e.toString().indexOf('max_verification_attempts_reached') !== -1)
		callback(false, true);
	else
	        callback(false);
} 
```

And for iOS : 
```
return [[self tanker] unlockCurrentDeviceWithPassword:registrationcode]
    .then(^() {
        success(true);
    })
    .catch(^(NSError* error) {
        success(false);
    });
```

I tested mostly on iOS and it appears that the Promise never resolve or reject.

**Comment by jeremad** [comment]
Thank you very much again for reporting this issue. This was actually a bug in our server (so not in this repository), we fixed it, and you should not encounter this issue again. Let us know if it's not the case!

Regards
