### ISSUE TITLE
Possible to initialize with own private key?

### ISSUE THREAD

**Issue by maxogden** [TankerHQ/sdk-js#7]
I have a use case where I want to integrate with an existing crypto system using a ed25519 private key I generated deterministically (e.g. https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki). Is it possible to create a user identity in Tanker by passing in the private key it should use?

**Comment by blastrock** [comment]
This is not what Tanker is intended for. Tanker is meant to be easy to use and as such it doesn't give control over the underlying keys. Moreover, users don't have a signature key, signature keys are per device.

Maybe you can clarify your use case, why do you need to use existing keys?

**Comment by cgestes** [comment]
I assume that you have a master key / wallet, from which you want to derive keys for different crypto coins or apps.

One way this could work is by using your own private key as an unlock key for the Tanker system. Let me explain:

Tanker’s architecture is as follows:

Devices have a signature and an encryption key pair, and every user has an encryption key pair, which is shared across that user’s devices. The public parts of all these key pairs are stored on the app’s Trustchain.

A Trustchain a set of signed and linked blocks, forming a datastore of cryptographic materials where each block either contains public information or has private but encrypted content, like the key pairs mentioned above.

The Trustchain itself also has a signature keypair, which is generated locally by the person who creates the Trustchain; the private part is shown once and never sent anywhere. This Trustchain private key is then used by the application server to sign a user’s first device.

Any additional device for a user can be added to the system using their unlock key. This key contains both a signature key and an encryption key, the first to prove that the new device is legitimate, and the latter to decrypt the private user key, which is retrieved from the Trustchain in encrypted form by the newly added device.

The unlock key, which is generated locally by a user’s first device, is part of the unlock mechanism, which was created to ensure that users never lose access to their encrypted data. The mechanism currently exists in two forms:

A true end-to-end flow, where the private unlock key never leaves the device and is exposed to the user once, putting the burden of storing it on them;
A more user-friendly flow (zero-access but not strictly end-to-end), where that locally generated unlock key is first encrypted using a secret that’s only known to the application server, and then stored on the Tanker unlock server. To retrieve their encrypted unlock key, the user must prove their identity to the unlock server, using a known factor like email, sms, a password, etc.

A possible third solution, which is currently not supported, would be to either use an external private key as the actual unlock key, or use it as a passphrase to encrypt the unlock key before sending it off to the unlock server.

Would either or both of these solutions match your use case?

Remco & Cedric

**Comment by jprichardson** [comment]
> One way this could work is by using your own private key as an unlock key for the Tanker system. 

I'm working with @maxogden on this project. This should work. At a very quick glance of the docs, I didn't see where we can set this private key. Will you point us in the right direction? Thank you.

**Comment by mremco** [comment]
Not exactly, and yes a little weird indeed. What we propose doesn’t involve the unlock email or password. You couldn’t find the proposed solutions in our docs, because they’re based on one or two things that haven’t been implemented yet:

- The creation of (part of) an unlock key by user input — currently, the [generation of an unlock key](https://docs.tanker.io/latest/api/tanker/#generateandregisterunlockkey) is done by the Tanker SDK after calling it;
- The possibility of encrypting the standard unlock key with a user-defined passphrase — currently, the unlock password doesn’t encrypt the unlock key, but it gets the unlock server to release the unlock key (encrypted with the user token).

Either solution would work.

Does that clear things up?

**Comment by maxogden** [comment]
@mremco Yes that makes sense, thank you.

**Comment by mremco** [comment]
Great, thanks @maxogden. I'm closing this issue now, hit us up if you need any assistance.

Best,
Remco
